config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    resources :shops, :only => [:index, :show] do

      resources :products, :only => [:show]

    end

    get '/shops/:shop_id/t/*id', :to => 'taxons#show', :as => :nested_shop_taxons

    namespace :admin do
      resources :shops

      resources :products do
        member do
          get :shop
          put :shop
        end
      end
    end

    namespace :api, defaults: { format: 'json' } do

      resource :session, controller: :user_session

      resources :users do
        collection do
          get :guest
        end
      end

      resources :shops, only: [:index, :show]
    end
  end

  mount Spree::Core::Engine, :at => '/'

end

app/models/shop.rb
class Shop < ActiveRecord::Base

  has_many :products_shops, :class_name => 'ProductsShops'
  has_many :products, :through => :products_shops

  has_many :prices, :class_name => 'Spree::Price'

  has_many :orders, :class_name => 'Spree::Order'

  belongs_to :user, :class_name => 'Spree::User'

  belongs_to :location, :class_name => 'Spree::Address', :foreign_key => :address_id

  after_create :create_products

  has_attached_file :photo,
                    styles: { small: '100x100>', normal: '500x500>' },
                    default_style: :small,
                    url: '/spree/shops/:id/:style/:basename.:extension',
                    path: ':rails_root/public/spree/shops/:id/:style/:basename.:extension',
                    default_url: '/assets/default_shop.png'

  validates_attachment :photo,
                       content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

  validates_presence_of :name

  delegate_belongs_to :location, :address

  geocoded_by :address
  after_validation :geocode

  def self.search(params)
    if params[:latitude].present? && params[:longitude].present?
      Shop.search_by_coordinates(params[:latitude], params[:longitude])
    elsif params[:address].present?
      Shop.search_by_address(params[:address])
    else
      Shop.all
    end
  end

  def rounded_distance_from(location)
    distance_from(location).round(2)
  end

  def opened?
    true
  end
  alias_method :opened, :opened?

  protected

  def self.search_by_coordinates(latitude, longitude)
    self.search_by([latitude, longitude])
  end

  def self.search_by_address(address)
    geocoded_location = Geokit::Geocoders::MultiGeocoder.geocode(address)
    self.search_by([geocoded_location.lat, geocoded_location.lng])
  end

  def self.search_by(location)
    Shop.near(location, Spree::Config[:shop_distance])
  end

  def create_products
    products = Spree::Product.all

    products.each do |product|
      shop_price = Spree::Price.new(:variant_id => product.master.id, :amount => product.price, :shop_id => self.id, :currency => Spree::Config[:currency])
      shop_price.save
    end
  end

end

app/controllers/spree/admin/shops_controller.rb
module Spree
  module Admin
    class ShopsController < ResourceController

      before_filter :build_address, :only => [:new, :edit]
      before_filter :save_address, :only => [:create, :update]

      def index
      end

      protected

      def model_class
        "#{controller_name.classify}".constantize
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= "1"

        params[:q][:s] ||= "name asc"
        @collection = super
        @collection = @collection.with_deleted if params[:q][:deleted_at_null] == '0'
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
            page(params[:page]).
            #per(Spree::Config[:admin_shops_per_page])
            per(10)

        @collection
      end

      def build_address
        @shop.location ||= Spree::Address.default
      end

      def save_address
        @shop.location ||= Spree::Address.default
        @shop.location.update_attributes(address_params)
      end

      def permitted_resource_params
        params.require(:shop).permit!
      end

      def address_params
        params[:shop].delete(:location)
      end

    end
  end
end

app/controllers/spree/api/shops_controller.rb
module Spree
  module Api
    class ShopsController < Spree::Api::BaseController
      def index
        @user_location = user_location(params[:user])
        @shops = Shop.accessible_by(current_ability, :read).search(params[:user])
        respond_with(@shops)
      end

      def show
        @shop = Shop.accessible_by(current_ability, :read).find(params[:id])
        @products = product_scope.ransack(params[:q]).result
      end

      private

      def user_location(params)
        if params[:latitude].present? && params[:longitude].present?
          [params[:latitude], params[:longitude]]
        elsif params[:address].present?
          params[:address]
        else
          nil
        end
      end
    end
  end
end

app/controllers/spree/shops_controller.rb
module Spree
  class ShopsController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @shops = Shop.search(params[:user])
      render 'spree/home/index'
    end

    def show
      @shop = Shop.find(params[:id])
      return unless @shop

      update_shop_reference

      @searcher = build_searcher(params.merge(:shop => @shop.id))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    private

    def update_shop_reference
      if !current_order.nil? && (current_order.shop_id.nil? || current_order.shop_id != @shop.id)
        current_order.empty!
        current_order.shop_id = @shop.id
        current_order.save!
      end
    end
  end
end

app/views/spree/admin/shops/_address_form.html.erb
<%= form.hidden_field :firstname, :value => '0' %>
<%= form.hidden_field :lastname, :value => '0' %>
<%= form.hidden_field :phone, :value => '0' %>
<div class="inner">
  <div class="field">
    <%= form.label :address1, Spree.t(:street_address) %><br />
    <%= form.text_field :address1, :class => 'required' %>
  </div>
  <div class="field">
    <%= form.label :city, Spree.t(:city) %><br />
    <%= form.text_field :city, :class => 'required' %>
  </div>
  <div class="field">
    <%= form.label :country_id, Spree.t(:country) %><br />
    <span id="country-selection">
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
    </span>
  </div>
  <div class="field">
    <%= form.label :zipcode, Spree.t(:zip) %><% if location.require_zipcode? %><br /><% end %>
    <%= form.text_field :zipcode, :class => "#{'required' if location.require_zipcode?}" %>
  </div>
</div>

app/views/spree/admin/shops/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @promotion } %>
<div class="row">
  <div id="general_fields" class="alpha thirteen columns">
    <div class="alpha nine columns">
      <%= f.field_container :name do %>
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'fullwidth' %>
      <% end %>

      <%= f.fields_for :location, @shop.location do |address_form| %>
          <%= render :partial => 'spree/admin/shops/address_form', :locals => { :form => address_form, :location => @shop.location } %>
      <% end %>

      <%= f.field_container :longitude do %>
          <%= f.label :longitude %>
          <%= f.text_field :longitude, :class => 'fullwidth', :disabled => true %>
      <% end %>

      <%= f.field_container :latitude do %>
          <%= f.label :latitude %>
          <%= f.text_field :latitude, :class => 'fullwidth', :disabled => true %>
      <% end %>

      <%= f.field_container :active do %>
          <%= f.label :active %>
          <%= f.check_box :active %>
      <% end %>

      <%= f.field_container :email do %>
          <%= f.label :email %>
          <%= f.text_field :email, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :public_phone do %>
          <%= f.label :public_phone %>
          <%= f.text_field :public_phone, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :private_phone do %>
          <%= f.label :private_phone %>
          <%= f.text_field :private_phone, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :rating do %>
          <%= f.label :rating %>
          <%= f.text_field :rating, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :service_hours_weekdays do %>
          <%= f.label :service_hours_weekdays %>
          <%= f.text_field :service_hours_weekdays, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :service_hours_friday do %>
          <%= f.label :service_hours_friday %>
          <%= f.text_field :service_hours_friday, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :service_hours_saturday do %>
          <%= f.label :service_hours_saturday %>
          <%= f.text_field :service_hours_saturday, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :payment_details do %>
          <%= f.label :payment_details %>
          <%= f.text_field :payment_details, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :min_delivery_time do %>
          <%= f.label :min_delivery_time %>
          <%= f.text_field :min_delivery_time, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :serving_area_radius do %>
          <%= f.label :serving_area_radius %>
          <%= f.text_field :serving_area_radius, :class => 'fullwidth' %>
      <% end %>

      <% if !f.object.nil? && f.object.photo.present? %>
          <%= link_to image_tag(f.object.photo.url(:small)), f.object.photo.url(:normal) %>
      <% end %>

      <%= f.field_container :photo do %>
          <%= f.label :photo %><br />
          <%= f.file_field :photo %>
      <% end %>

    </div>
  </div>
</div>

app/views/spree/admin/shops/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_shop) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_shops_list), admin_shops_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<%= form_for @shop, :url => object_url, :method => :put do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/shops/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:listing_shops) %>
<% end %>

<% content_for :page_actions do %>
    <li id="new_shop_link">
      <%= button_link_to Spree.t(:new_shop), new_object_url, {:icon => 'plus', :id => 'admin_new_shop' } %>
    </li>
<% end if can?(:create, Shop) %>

<% content_for :table_filter_title do %>
    <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
    <div data-hook="admin_shops_sidebar">

      <%= search_form_for [:admin, @search] do |f| %>

          <%- locals = {:f => f} %>

          <div data-hook="admin_shops_index_search">
            <div class="alpha nine columns">
              <div class="field">
                <%= f.label :name_cont, Spree.t(:name) %>
                <%= f.text_field :name_cont, :size => 15 %>
              </div>
            </div>
          </div>

          <div class="clear"></div>

          <div class="form-buttons actions filter-actions" data-hook="admin_shops_index_search_buttons">
            <%= button Spree.t(:search), 'search' %>
          </div>
      <% end %>
    </div>
<% end %>

<div id="new_shop_wrapper" data-hook></div>

<%= paginate @collection %>

<% if @collection.any? %>
    <table class="index" id="listing_shops">
      <colgroup>
        <col style="width: 85%;">
        <col style="width: 15%;">
      </colgroup>
      <thead>
      <tr data-hook="admin_shops_index_headers">
        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { :default_order => "desc" }, {:title => 'admin_shops_listing_name_title'} %></th>
        <th data-hook="admin_shops_index_header_actions" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @collection.each do |shop| %>
          <tr id="<%= spree_dom_id shop %>" data-hook="admin_shops_index_rows" class="<%= cycle('odd', 'even') %>">
            <td><%= link_to shop.try(:name), edit_admin_shop_path(shop) %></td>
            <td class="actions" data-hook="admin_shops_index_row_actions">
              <%= link_to_edit shop, :no_text => true, :class => 'edit' if can?(:edit, shop) %>
              &nbsp;
              <%= link_to_delete shop, :no_text => true if can?(:delete, shop) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alpha twelve columns no-objects-found">
      <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/shop')) %>,
      <%= link_to Spree.t(:add_one), spree.new_admin_shop_path %>!
    </div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/shops/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_shop) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_shops_list), spree.admin_shops_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<%= form_for :shop, :url => collection_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>