config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    resources :shops, :only => [:index, :show] do

      resources :products, :only => [:show]

    end

    get '/shops/:shop_id/t/*id', :to => 'taxons#show', :as => :nested_shop_taxons

    namespace :admin do
      resources :shops

      resources :products do
        member do
          get :shop
          put :shop
        end
      end
    end

    namespace :api, defaults: { format: 'json' } do

      resource :session, controller: :user_session

      resources :users do
        collection do
          get :guest
        end
      end

      resources :shops, only: [:index, :show]
    end
  end

  mount Spree::Core::Engine, :at => '/'

end

app/views/spree/admin/products/_shop_form.html.erb
<div data-hook="admin_product_form_fields">

  <div class="right four columns omega" data-hook="admin_product_form_right">
    <div data-hook="admin_product_form_price">
      <%= f.field_container :price do %>
          <%= f.label :shop_price, Spree.t(:shop_price) %>
          <%= f.text_field :shop_price, :value => number_to_currency(@product.shop_price(spree_current_user.shop).price, :unit => '') %>
          <%= f.error_message_on :shop_price %>
      <% end %>
    </div>

  </div>

  <div class="clear"></div>

  <div data-hook="admin_product_form_additional_fields"></div>

  <div class="clear"></div>
</div>

<% unless Rails.env.test? %>
    <script>
        $('.select2-container').css({width: '20em'})
    </script>
<% end %>

app/views/spree/admin/products/shop.html.erb
<% content_for :page_actions do %>
    <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Manage' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :method => :put, :url => shop_admin_product_url, :html => { :multipart => true } do |f| %>
    <fieldset class="no-border-top">
      <%= render :partial => 'shop_form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </fieldset>
<% end %>