config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    resources :shops, :only => [:index, :show] do

      resources :products, :only => [:show]

    end

    get '/shops/:shop_id/t/*id', :to => 'taxons#show', :as => :nested_shop_taxons

    namespace :admin do
      resources :shops

      resources :products do
        member do
          get :shop
          put :shop
        end
      end
    end

    namespace :api, defaults: { format: 'json' } do

      resource :session, controller: :user_session

      resources :users do
        collection do
          get :guest
        end
      end

      resources :shops, only: [:index, :show]
    end
  end

  mount Spree::Core::Engine, :at => '/'

end

app/views/admin/products/_edit_link.html.erb
<% if spree_current_user.has_spree_role?('manager') %>
    <%= link_to product.try(:name), shop_admin_product_path(product) %>
<% else %>
    <%= link_to product.try(:name), edit_admin_product_path(product) %>
<% end %>

app/views/admin/products/_edit_tab_link.html.erb
<% end if can?(:edit, Spree::Product) %>

app/views/admin/products/_manage_tab.html.erb
<%= content_tag :li, :class => ('active' if current == 'Manage') do %>
    <%= link_to_with_icon 'edit', Spree.t(:product_manage), shop_admin_product_url(@product) %>
<% end if can?(:shop, Spree::Product) %>

app/views/admin/products/_shop_price.html.erb
<% if spree_current_user.has_spree_role?('manager') %>
    <%= product.display_shop_price(spree_current_user.shop).to_html rescue '' %>
<% else %>
    <%= product.display_price.to_html rescue '' %>
<% end %>